apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: hubble-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
