apiVersion: v1
kind: Service
metadata:
  name: hubble-relay-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: hubble-relay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4245
  type: LoadBalancer
