kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
name: 1-cilium
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraMounts:
    - hostPath: /volumes/kind-control-plane/ext4fs.img
      containerPath: /var/csi/rawfile/ext4fs.img
  - role: worker
    labels:
      topology.kubernetes.io/zone: zone-a
    extraMounts:
    - hostPath: /volumes/kind-worker/ext4fs.img
      containerPath: /var/csi/rawfile/ext4fs.img
  - role: worker
    labels:
      topology.kubernetes.io/zone: zone-b
    extraMounts:
    - hostPath: /volumes/kind-worker2/ext4fs.img
      containerPath: /var/csi/rawfile/ext4fs.img
  - role: worker
    labels:
      topology.kubernetes.io/zone: zone-c
    extraMounts:
    - hostPath: /volumes/kind-worker3/ext4fs.img
      containerPath: /var/csi/rawfile/ext4fs.img
